### ISSUE TITLE
order of axes for 3D spatial image

### ISSUE THREAD

**Issue by giovp** [spatial-image/spatial-image#14]
hi @thewtex ,

currently, a 3d spatial-image has dimensions `("z", "y", "x", "c")`. This order cannot be written to NGFF due to constraints on the channel axis always before spatial dimensions axes https://github.com/scverse/spatialdata/issues/84.
Considering that for time it exist both `("t", "y", "x", "c")` and `("t", "c", "y", "x")`, do you think it'd be possible to have the same for the `z` case, so a spatial-image class with dimensions `("c","z", "y", "x",)` ? This would match ngff specs v0.4.

Curious to hear what you think and happy to contribute in case.

afaik this would be only a temporary fix, as for v0.5 this constraint will be lifted.

Thanks!

**Comment by thewtex** [comment]
@giovp yes -- thank you for the contribution!

We have three primary dimension orders that important because of the associated memory layouts and how their use in the ecosystem:

- `("c", "z", "y", "x")`, i.e. channel continguous, which is important for CNN libraries, e.g. pytorch
- `("z", "c", "y", "x")`, this corresponds to the memory layout of OME-TIFF
- `("z", "y", "x", "c")`, i.e. channel interleaved, which is important for image processing, e.g. itk, scikit-image, and visualization tools

**Comment by giovp** [comment]
closed by #16
